# Generated by Django 4.0.3 on 2022-07-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_user_pas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pas',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
