# Generated by Django 4.0.3 on 2022-07-24 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_user_pas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pas',
            new_name='password',
        ),
    ]
