# Generated by Django 4.0.3 on 2022-07-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_customuser_delete_user_delete_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='doctor',
            new_name='is_doctor',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_patient',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('is_doctor', 'doctor'), ('is_patient', 'patient')], default=models.BooleanField(default=True), max_length=10),
        ),
    ]
