# Generated by Django 4.0.3 on 2022-07-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_customuser_address_customuser_city_customuser_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pin',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
